//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rezervasyonAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparisler()
        {
            this.SiparisDetays = new HashSet<SiparisDetay>();
        }
    
        public int SiparisID { get; set; }
        public Nullable<int> MasaID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<System.DateTime> TarihSaat { get; set; }
        public string OdemeDurumu { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Masalar Masalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetay> SiparisDetays { get; set; }
    }
}
